apiVersion: v1
kind: ConfigMap
metadata:
  name: resume-app-config
  namespace: devops-resume
  labels:
    app.kubernetes.io/name: devops-resume-platform
    app.kubernetes.io/part-of: devops-resume-platform
data:
  # Application configuration
  NODE_ENV: "production"
  PORT: "8080"
  
  # Monitoring configuration
  ENABLE_METRICS: "true"
  METRICS_PATH: "/metrics"
  
  # Health check configuration
  HEALTH_CHECK_PATH: "/health"
  HEALTH_CHECK_INTERVAL: "30s"
  
  # Logging configuration
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"

