# Traefik static configuration
api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: resume-network
  kubernetes:
    endpoints:
      - "https://kubernetes.default.svc:443"
    token: /var/run/secrets/kubernetes.io/serviceaccount/token
    certAuthFilePath: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    namespaces:
      - default
      - devops-resume

certificatesResolvers:
  letsencrypt:
    acme:
      email: your-email@example.com
      storage: /etc/traefik/certs/acme.json
      httpChallenge:
        entryPoint: web
      tlsChallenge: {}

log:
  level: INFO
  filePath: "/var/log/traefik.log"

accessLog:
  filePath: "/var/log/access.log"
  format: json

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true

tracing:
  jaeger:
    samplingType: const
    samplingParam: 1.0
    localAgentHostPort: "jaeger:6831"

ping:
  entryPoint: "traefik"

serversTransport:
  insecureSkipVerify: false
  maxIdleConnsPerHost: 10

